/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ExclusiveNFTFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "deployExclusiveToken" | "getTotalCollection" | "tokens"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ExclusiveNFTCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployExclusiveToken",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCollection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployExclusiveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
}

export namespace ExclusiveNFTCreatedEvent {
  export type InputTuple = [owner: AddressLike, tokenAddress: AddressLike];
  export type OutputTuple = [owner: string, tokenAddress: string];
  export interface OutputObject {
    owner: string;
    tokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExclusiveNFTFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ExclusiveNFTFactory;
  waitForDeployment(): Promise<this>;

  interface: ExclusiveNFTFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployExclusiveToken: TypedContractMethod<
    [name: string, symbol: string, unrevealURI: string],
    [string],
    "nonpayable"
  >;

  getTotalCollection: TypedContractMethod<[], [bigint], "view">;

  tokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployExclusiveToken"
  ): TypedContractMethod<
    [name: string, symbol: string, unrevealURI: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTotalCollection"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "ExclusiveNFTCreated"
  ): TypedContractEvent<
    ExclusiveNFTCreatedEvent.InputTuple,
    ExclusiveNFTCreatedEvent.OutputTuple,
    ExclusiveNFTCreatedEvent.OutputObject
  >;

  filters: {
    "ExclusiveNFTCreated(address,address)": TypedContractEvent<
      ExclusiveNFTCreatedEvent.InputTuple,
      ExclusiveNFTCreatedEvent.OutputTuple,
      ExclusiveNFTCreatedEvent.OutputObject
    >;
    ExclusiveNFTCreated: TypedContractEvent<
      ExclusiveNFTCreatedEvent.InputTuple,
      ExclusiveNFTCreatedEvent.OutputTuple,
      ExclusiveNFTCreatedEvent.OutputObject
    >;
  };
}
