/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
import type * as nexthypeNftSol from "./NexthypeNFT.sol";
export type { nexthypeNftSol };
import type * as utils from "./utils";
export type { utils };
export type { DestinationMinter } from "./DestinationMinter";
export type { PremiumNFT } from "./PremiumNFT";
export type { SourceMinter } from "./SourceMinter";
