/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MysteryEventFactoryInterface extends utils.Interface {
  functions: {
    "deployMysteryEvent(string,string,string,address,uint64,uint256,string,uint64)": FunctionFragment;
    "events(uint256)": FunctionFragment;
    "getTotalEvents()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deployMysteryEvent" | "events" | "getTotalEvents"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployMysteryEvent",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "events",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalEvents",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deployMysteryEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalEvents",
    data: BytesLike
  ): Result;

  events: {
    "MysteryEventCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MysteryEventCreated"): EventFragment;
}

export interface MysteryEventCreatedEventObject {
  owner: string;
  tokenAddress: string;
}
export type MysteryEventCreatedEvent = TypedEvent<
  [string, string],
  MysteryEventCreatedEventObject
>;

export type MysteryEventCreatedEventFilter =
  TypedEventFilter<MysteryEventCreatedEvent>;

export interface MysteryEventFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MysteryEventFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployMysteryEvent(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      unrevealedURI: PromiseOrValue<string>,
      premiumNFT: PromiseOrValue<string>,
      _nftPurchasedRequired: PromiseOrValue<BigNumberish>,
      maxSupply: PromiseOrValue<BigNumberish>,
      baseURI: PromiseOrValue<string>,
      clSubscriptionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    events(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTotalEvents(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;
  };

  deployMysteryEvent(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    unrevealedURI: PromiseOrValue<string>,
    premiumNFT: PromiseOrValue<string>,
    _nftPurchasedRequired: PromiseOrValue<BigNumberish>,
    maxSupply: PromiseOrValue<BigNumberish>,
    baseURI: PromiseOrValue<string>,
    clSubscriptionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  events(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getTotalEvents(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    deployMysteryEvent(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      unrevealedURI: PromiseOrValue<string>,
      premiumNFT: PromiseOrValue<string>,
      _nftPurchasedRequired: PromiseOrValue<BigNumberish>,
      maxSupply: PromiseOrValue<BigNumberish>,
      baseURI: PromiseOrValue<string>,
      clSubscriptionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    events(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getTotalEvents(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "MysteryEventCreated(address,address)"(
      owner?: null,
      tokenAddress?: null
    ): MysteryEventCreatedEventFilter;
    MysteryEventCreated(
      owner?: null,
      tokenAddress?: null
    ): MysteryEventCreatedEventFilter;
  };

  estimateGas: {
    deployMysteryEvent(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      unrevealedURI: PromiseOrValue<string>,
      premiumNFT: PromiseOrValue<string>,
      _nftPurchasedRequired: PromiseOrValue<BigNumberish>,
      maxSupply: PromiseOrValue<BigNumberish>,
      baseURI: PromiseOrValue<string>,
      clSubscriptionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    events(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalEvents(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deployMysteryEvent(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      unrevealedURI: PromiseOrValue<string>,
      premiumNFT: PromiseOrValue<string>,
      _nftPurchasedRequired: PromiseOrValue<BigNumberish>,
      maxSupply: PromiseOrValue<BigNumberish>,
      baseURI: PromiseOrValue<string>,
      clSubscriptionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    events(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalEvents(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
