/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PremiumFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployGenerativeToken"
      | "getTotalPremiumCollection"
      | "tokens"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PremiumTokenCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployGenerativeToken",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPremiumCollection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployGenerativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPremiumCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
}

export namespace PremiumTokenCreatedEvent {
  export type InputTuple = [owner: AddressLike, tokenAddress: AddressLike];
  export type OutputTuple = [owner: string, tokenAddress: string];
  export interface OutputObject {
    owner: string;
    tokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PremiumFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PremiumFactory;
  waitForDeployment(): Promise<this>;

  interface: PremiumFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployGenerativeToken: TypedContractMethod<
    [token_uri: string, subscriptionPrice: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  getTotalPremiumCollection: TypedContractMethod<[], [bigint], "view">;

  tokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployGenerativeToken"
  ): TypedContractMethod<
    [token_uri: string, subscriptionPrice: BigNumberish[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTotalPremiumCollection"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "PremiumTokenCreated"
  ): TypedContractEvent<
    PremiumTokenCreatedEvent.InputTuple,
    PremiumTokenCreatedEvent.OutputTuple,
    PremiumTokenCreatedEvent.OutputObject
  >;

  filters: {
    "PremiumTokenCreated(address,address)": TypedContractEvent<
      PremiumTokenCreatedEvent.InputTuple,
      PremiumTokenCreatedEvent.OutputTuple,
      PremiumTokenCreatedEvent.OutputObject
    >;
    PremiumTokenCreated: TypedContractEvent<
      PremiumTokenCreatedEvent.InputTuple,
      PremiumTokenCreatedEvent.OutputTuple,
      PremiumTokenCreatedEvent.OutputObject
    >;
  };
}
