/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface PremiumFactoryInterface extends utils.Interface {
  functions: {
    "deployGenerativeToken(string,uint256[])": FunctionFragment;
    "getTotalPremiumCollection()": FunctionFragment;
    "tokens(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deployGenerativeToken"
      | "getTotalPremiumCollection"
      | "tokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployGenerativeToken",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPremiumCollection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployGenerativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPremiumCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;

  events: {
    "PremiumTokenCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PremiumTokenCreated"): EventFragment;
}

export interface PremiumTokenCreatedEventObject {
  owner: string;
  tokenAddress: string;
}
export type PremiumTokenCreatedEvent = TypedEvent<
  [string, string],
  PremiumTokenCreatedEventObject
>;

export type PremiumTokenCreatedEventFilter =
  TypedEventFilter<PremiumTokenCreatedEvent>;

export interface PremiumFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PremiumFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployGenerativeToken(
      token_uri: PromiseOrValue<string>,
      subscriptionPrice: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getTotalPremiumCollection(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  deployGenerativeToken(
    token_uri: PromiseOrValue<string>,
    subscriptionPrice: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getTotalPremiumCollection(overrides?: CallOverrides): Promise<BigNumber>;

  tokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    deployGenerativeToken(
      token_uri: PromiseOrValue<string>,
      subscriptionPrice: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<string>;

    getTotalPremiumCollection(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "PremiumTokenCreated(address,address)"(
      owner?: null,
      tokenAddress?: null
    ): PremiumTokenCreatedEventFilter;
    PremiumTokenCreated(
      owner?: null,
      tokenAddress?: null
    ): PremiumTokenCreatedEventFilter;
  };

  estimateGas: {
    deployGenerativeToken(
      token_uri: PromiseOrValue<string>,
      subscriptionPrice: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getTotalPremiumCollection(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployGenerativeToken(
      token_uri: PromiseOrValue<string>,
      subscriptionPrice: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getTotalPremiumCollection(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
